# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='head_img',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to='uploads'),
        ),
    ]
