# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20170721_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='head_img',
            field=models.ImageField(default=1, upload_to='uploads.media', verbose_name='文章标题图片'),
            preserve_default=False,
        ),
    ]
