# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-16 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertrackrecord',
            name='status',
            field=models.IntegerField(choices=[(1, '近期无报名计划'), (2, '2个月内报名'), (3, '1个月内报名'), (4, '2周内报名'), (5, '1周内报名'), (6, '2天内报名'), (7, '已报名')], default=2, help_text='选择客户此时的状态', verbose_name='状态'),
        ),
    ]
