# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20170716_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='courserecord',
            options={'verbose_name': '课程记录', 'verbose_name_plural': '课程记录'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '消费者(学生)', 'verbose_name_plural': '消费者(学生)'},
        ),
        migrations.AlterModelOptions(
            name='customertrackrecord',
            options={'verbose_name': '咨询记录', 'verbose_name_plural': '咨询记录'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': '学校', 'verbose_name_plural': '学校'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('view_customer_list', '查看客户列表'), ('view_customer_info', '查看客户详情'), ('edit_own_customer_info', '编辑客户信息')), 'verbose_name': '工作人员', 'verbose_name_plural': '工作人员'},
        ),
        migrations.AlterField(
            model_name='courserecord',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ClassList', verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='consult_memo',
            field=models.TextField(verbose_name='咨询记录'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='course_type',
            field=models.CharField(choices=[('online', '网络班'), ('offline_weekend', '面授班(周末)'), ('offline_fulltime', '面授班(脱产)')], default='offline_weekend', max_length=64, verbose_name='课程类型'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='qq',
            field=models.CharField(max_length=64, unique=True, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source_type',
            field=models.CharField(choices=[('qq', 'qq群'), ('referral', '内部转介绍'), ('51cto', '51cto'), ('agent', '招生代理'), ('others', '其他')], max_length=64, verbose_name='客户来源'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('signed', '已报名'), ('unregistered', '未报名'), ('graduated', '已毕业'), ('drop-off', '退学')], max_length=64, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='customertrackrecord',
            name='track_date',
            field=models.DateField(auto_now_add=True, verbose_name='咨询日期'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='上课日期'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='学生姓名'),
        ),
    ]
